import cron from 'node-cron';
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

// Load environment variables
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '.env') });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing Supabase configuration locally. Make sure .env has VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const smtpEmail = process.env.SMTP_EMAIL || '21054cs051@gmail.com';

const sendExpirationAlerts = async () => {
  console.log(`[${new Date().toISOString()}] Initiating License Expiration Check...`);

  try {
    // We get all products with active genuine status. 
    // Wait, the dates are stored in fssai_licenses primarily, and mirrored in products.
    // Let's pull directly from the products table for simplicity, assuming we only check products.
    // However, AddProductPage stores `valid_until` into `fssai_licenses`.
    // Let's query fssai_licenses.
    const { data: licenses, error } = await supabase
      .from('fssai_licenses')
      .select('license_number, company_name, valid_until, status');

    if (error) {
      throw error;
    }

    const today = new Date();
    const expiringLicenses = [];

    // Filter for licenses expiring in <= 30 days that are not acknowledged
    licenses.forEach((lic) => {
      if (!lic.valid_until || lic.status === 'acknowledged') return;

      const expireDate = new Date(lic.valid_until);
      const diffTime = expireDate.getTime() - today.getTime();
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

      if (diffDays <= 30 && diffDays >= 0) {
        expiringLicenses.push({
          ...lic,
          daysLeft: diffDays
        });
      } else if (diffDays < 0) {
        // Already expired
        expiringLicenses.push({
          ...lic,
          daysLeft: diffDays
        });
      }
    });

    if (expiringLicenses.length === 0) {
      console.log("No licenses are expiring within 30 days. No email dispatched.");
      return;
    }

    console.log(`Found ${expiringLicenses.length} expiring licenses. Constructing email...`);

    let emailHtml = `
      <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px; border: 1px solid #eee; border-radius: 8px;">
        <h2 style="color: #1C5C48;">⚠️ Automated License Expiry Alert</h2>
        <p>The following food product FSSAI licenses are expiring in the next 30 days (or have already expired). Immediate action is required to ensure compliance.</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          <thead>
            <tr style="background-color: #f4f7fa; text-align: left;">
              <th style="padding: 12px; border-bottom: 2px solid #ddd;">Manufacturer</th>
              <th style="padding: 12px; border-bottom: 2px solid #ddd;">FSSAI Number</th>
              <th style="padding: 12px; border-bottom: 2px solid #ddd;">Expiration</th>
              <th style="padding: 12px; border-bottom: 2px solid #ddd;">Status</th>
            </tr>
          </thead>
          <tbody>
    `;

    expiringLicenses.sort((a, b) => a.daysLeft - b.daysLeft).forEach(lic => {
      const statusColor = lic.daysLeft < 0 ? 'red' : 'darkorange';
      const statusText = lic.daysLeft < 0 ? 'EXPIRED' : `${lic.daysLeft} days left`;
      
      emailHtml += `
        <tr>
          <td style="padding: 12px; border-bottom: 1px solid #eee;"><strong>${lic.company_name}</strong></td>
          <td style="padding: 12px; border-bottom: 1px solid #eee; font-family: monospace;">${lic.license_number}</td>
          <td style="padding: 12px; border-bottom: 1px solid #eee;">${lic.valid_until}</td>
          <td style="padding: 12px; border-bottom: 1px solid #eee; color: ${statusColor}; font-weight: bold;">${statusText}</td>
        </tr>
      `;
    });

    emailHtml += `
          </tbody>
        </table>
        <p style="margin-top: 30px; font-size: 12px; color: #888;">This is an automated 11:00 AM daily alert generated by the TrustVerify Cron Daemon.</p>
      </div>
    `;

    try {
      const response = await fetch(`https://formsubmit.co/ajax/${smtpEmail}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Accept": "application/json",
          "Origin": "http://localhost:5173",
          "Referer": "http://localhost:5173/"
        },
        body: JSON.stringify({
          _subject: `CRITICAL: ${expiringLicenses.length} Food Product Licenses Expiring!`,
          message: `You have ${expiringLicenses.length} licenses expiring in the next 30 days. Log into the admin portal to manage them.`,
          _template: 'box',
          Report: emailHtml
        })
      });
      
      const responseData = await response.json();
      console.log(`[SUCCESS] Email sent successfully to ${smtpEmail}:`, responseData);
    } catch (fetchError) {
      console.error("[ERROR] FormSubmit dispatch failed:", fetchError);
    }
    
  } catch (error) {
    console.error("Error checking licenses or sending email:", error);
  }
};

// --- CRON SCHEDULER SETUP ---
// Format: minute hour dayOfMonth month dayOfWeek
// "0 11 * * *" = 11:00 AM every single day.
console.log("===================================================================");
console.log(`🚀 Starting Scheduled Automated CRON Service`);
console.log(`📦 Targeted Admin Inbox: ${smtpEmail}`);
console.log(`🕒 Job scheduled unconditionally for 11:00 AM every day.`);
console.log("===================================================================");

cron.schedule('0 11 * * *', () => {
  console.log("⏰ 11:00 AM reached. Executing scheduled expiration checks...");
  sendExpirationAlerts();
}, {
  scheduled: true,
  timezone: "Asia/Kolkata" // Assuming Indian IST Standard Time given previous FSSAI context. Can be removed for local system time.
});

// Run it once immediately if --test flag is passed
if (process.argv.includes('--test')) {
  console.log("TEST MODE ACTIVATED. Running a forced check right now...");
  sendExpirationAlerts();
}
