// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function stripQuotes(s: string): string {
  const t = s.trim();
  if ((t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'"))) {
    return t.slice(1, -1).trim();
  }
  return t;
}

const SUPABASE_URL_RAW = stripQuotes(
  (import.meta.env.VITE_SUPABASE_URL as string | undefined) ?? '',
);
const SUPABASE_PUBLISHABLE_KEY_RAW = stripQuotes(
  ((import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
    import.meta.env.VITE_SUPABASE_ANON_KEY) as string | undefined) ?? '',
);

function normalizeHttpUrl(url: string): string {
  const u = url.trim().replace(/\/+$/, '');
  if (!u) return '';
  try {
    const parsed = new URL(u);
    if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') return '';
    return u;
  } catch {
    return '';
  }
}

/** Real project URL (also used after production build). */
export const SUPABASE_URL = normalizeHttpUrl(SUPABASE_URL_RAW);
export const SUPABASE_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY_RAW.trim();

/**
 * In Vite dev, use the local proxy so the browser never resolves *.supabase.co
 * (fixes net::ERR_NAME_NOT_RESOLVED on some DNS / corporate networks).
 * Production uses the real https URL.
 */
export function getSupabaseUrlForThisEnvironment(): string {
  if (!SUPABASE_URL) return '';
  if (import.meta.env.DEV && typeof window !== 'undefined') {
    return `${window.location.origin.replace(/\/+$/, '')}/supabase-api`;
  }
  return SUPABASE_URL;
}

export function isSupabaseConfigured(): boolean {
  return Boolean(SUPABASE_URL.length && SUPABASE_PUBLISHABLE_KEY.length);
}

export const supabase = createClient<Database>(
  getSupabaseUrlForThisEnvironment(),
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
