import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PdfData {
  productName: string;
  manufacturer: string;
  licenseNumber: string;
  trustScore: number;
  status: string;
  verifiedAt: string;
}

export const generateCertificate = (data: PdfData) => {
  const doc = new jsPDF();
  
  // Colors
  const primaryColor: [number, number, number] = [28, 92, 72];
  let statusColor: [number, number, number] = [50, 50, 50]; // Default dark
  
  if (data.status === 'genuine') statusColor = [39, 174, 96]; // Green
  else if (data.status === 'suspicious') statusColor = [243, 156, 18]; // Orange
  else if (data.status === 'fake') statusColor = [192, 57, 43]; // Red

  // Header Background
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 40, 'F');

  // Header Text
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text('Product Authenticity Certificate', 105, 20, { align: 'center' });
  
  doc.setFontSize(11);
  doc.setTextColor(220, 220, 220);
  doc.text('Officially verified and generated by the Administrative System', 105, 30, { align: 'center' });
  
  // Body Title
  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text('Verification Details', 14, 55);
  
  autoTable(doc, {
    startY: 65,
    margin: { left: 14, right: 14 },
    head: [['Field', 'Details']],
    body: [
      ['Product Name', data.productName || 'Unknown Product'],
      ['Manufacturer / Brand', data.manufacturer || 'Unknown Manufacturer'],
      ['FSSAI License Number', data.licenseNumber || 'Not Provided'],
      ['Computed Trust Score', `${data.trustScore} / 100`],
      ['Verification Status', data.status.toUpperCase()],
      ['Verification Timestamp', new Date(data.verifiedAt).toLocaleString()],
    ],
    theme: 'grid',
    styles: { fontSize: 12, cellPadding: 6 },
    headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 80, fillColor: [248, 250, 252] },
      1: { cellWidth: 'auto' }
    },
    didParseCell: function(dataItem) {
      // Colorize the Status row specifically
      if (dataItem.section === 'body' && dataItem.row.index === 4 && dataItem.column.index === 1) {
        dataItem.cell.styles.textColor = statusColor;
        dataItem.cell.styles.fontStyle = 'bold';
      }
    }
  });

  // Unique Seal / Identifier Section
  const finalY = (doc as any).lastAutoTable.finalY + 20;
  
  doc.setFontSize(12);
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.text(`STATUS: ${data.status.toUpperCase()}`, 105, finalY, { align: 'center' });

  const uniqueId = `CERT-${data.licenseNumber || '0000'}-${Date.now().toString().slice(-6)}`;

  // Digital Signature Block
  const sigW = 92;
  const sigH = 32;
  const sigX = 196 - sigW; 
  const sigY = finalY + 15;

  // Box Frame
  doc.setDrawColor(0);
  doc.setLineWidth(0.2);
  doc.rect(sigX, sigY, sigW, sigH);

  // Draw Checkmark - Drop shadow
  doc.setDrawColor(0); // Black shadow
  doc.setLineWidth(4);
  doc.line(sigX + 50 + 1.5, sigY + 18 + 1.5, sigX + 58 + 1.5, sigY + 28 + 1.5);
  doc.line(sigX + 58 + 1.5, sigY + 28 + 1.5, sigX + 75 + 1.5, sigY + 4 + 1.5);

  // Draw Checkmark - Green
  doc.setDrawColor(0, 153, 51); // Green color
  doc.setLineWidth(4);
  doc.line(sigX + 50, sigY + 18, sigX + 58, sigY + 28);
  doc.line(sigX + 58, sigY + 28, sigX + 75, sigY + 4);
  
  doc.setFont("helvetica", "normal");
  
  // Header Text
  doc.setFontSize(16);
  doc.setTextColor(0, 51, 102); // Dark navy blue
  doc.text("Signature valid", sigX + 2, sigY + 7);
  
  // Details Text
  doc.setFontSize(9);
  doc.setTextColor(50, 70, 90);
  doc.text("Digitally signed by TrustVerify Admin", sigX + 2, sigY + 13);
  
  const d = new Date(data.verifiedAt);
  const pad = (n: number) => n.toString().padStart(2, '0');
  const dStr = `${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())} +05:30`;
  doc.text(`Date: ${dStr}`, sigX + 2, sigY + 18);
  
  const statusReason = data.status === 'genuine' ? "Verified Genuine Product" : "Authenticity Verified";
  doc.text(`Reason: ${statusReason}`, sigX + 2, sigY + 23);
  doc.text(`Location: TrustVerify Servers, IND`, sigX + 2, sigY + 28);

  // Footer
  const pageCount = (doc.internal as any).getNumberOfPages();
  doc.setFontSize(9);
  doc.setTextColor(150);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(`Certificate ID: ${uniqueId}`, 14, 285);
    doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: 'right' });
  }
  
  // Save/Download
  doc.save(`Authenticity_Certificate_${data.licenseNumber || 'Product'}.pdf`);
};
